/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb4a8",
        "secondary": "#576500",
        "on-primary-container": "#fffbff",
        "surface-variant": "#e5e2e1",
        "on-secondary-fixed-variant": "#414c00",
        "surface-container-highest": "#e5e2e1",
        "background": "#fcf9f8",
        "on-background": "#1c1b1b",
        "on-primary-fixed-variant": "#4330aa",
        "surface-tint": "#5c4bc3",
        "primary": "#5949c0",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0edec",
        "tertiary": "#b22215",
        "secondary-fixed-dim": "#b8d315",
        "on-primary-fixed": "#180065",
        "surface-dim": "#dcd9d9",
        "outline": "#787584",
        "secondary-fixed": "#d4f039",
        "outline-variant": "#c9c4d5",
        "on-secondary-fixed": "#191e00",
        "inverse-on-surface": "#f3f0ef",
        "surface-container-high": "#ebe7e7",
        "surface": "#fcf9f8",
        "on-surface-variant": "#474553",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "inverse-surface": "#313030",
        "tertiary-container": "#d53c2b",
        "on-surface": "#1c1b1b",
        "primary-fixed": "#e5deff",
        "surface-bright": "#fcf9f8",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffdad4",
        "on-tertiary-fixed": "#410000",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#c7bfff",
        "primary-container": "#7263db",
        "inverse-primary": "#c7bfff",
        "on-secondary-container": "#5c6b00",
        "secondary-container": "#d4f039",
        "on-tertiary-fixed-variant": "#920401",
        "on-tertiary-container": "#fffbff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "40px",
        "hard-shadow": "4px 4px 0px #0A0A0A",
        "margin-mobile": "16px",
        "border-width-heavy": "3px",
        "border-width": "2px"
      },
      fontFamily: {
        "label-mono-sm": ["Space Mono", "monospace"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "label-mono": ["Space Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "display-xl": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "label-mono-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.1", letterSpacing: "0em", fontWeight: "700" }],
        "label-mono": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.0", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-xl": ["80px", { lineHeight: "0.95", letterSpacing: "-0.04em", fontWeight: "900" }]
      }
    },
  },
  plugins: [],
}
